tasks:
  - name: install google-cloud-sdk & gcloud configs
    init: |
      pip install -r requirements.txt
      pip install jupytext openpyxl optuna pandas_gbq scikit-learn lightgbm
      PY_VERSION=$(python -V| awk '{l=$2} END {print l}')
      cp ipaexg.ttf /home/gitpod/.pyenv/versions/$PY_VERSION/lib/python3.8/site-packages/matplotlib/mpl-data/fonts/ttf/
      # pip がバージョンアップされ、インストール先が変わるのについて行く方式に変更。
      # st.write(matplotlib.matplotlib_fname()) してmatplotlibのインストール先を確認できる
      # cp ipaexg.ttf /workspace/.pip-modules/lib/python3.8/site-packages/matplotlib/mpl-data/fonts/ttf/
      wget https://www.jpx.co.jp/markets/statistics-equities/misc/tvdivq0000001vg2-att/data_j.xls
      gp sync-done streamlit
  - name: streamlit run
    init: |
      gp sync-await streamlit
      streamlit run streamlit_jpx.py
    openMode: split-right
  - name: jupyter notebook run
    init: |
      gp sync-await streamlit
      jupyter notebook --generate-config
      echo -e '\nc.NotebookApp.contents_manager_class = "jupytext.TextFileContentsManager"' >> ~/.jupyter/jupyter_notebook_config.py
      echo -e '\nc.ContentsManager.default_jupytext_formats = "ipynb,py"' >> ~/.jupyter/jupyter_notebook_config.py
      jupyter notebook --ip=*
    openMode: split-right
  # - name: install google-cloud-sdk & gcloud configs
  #   init: |
  #     curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-358.0.0-linux-x86_64.tar.gz
  #     tar -xvf google-cloud-sdk-358.0.0-linux-x86_64.tar.gz
  #     ./google-cloud-sdk/install.sh
  #     rm google-cloud-sdk-358.0.0-linux-x86_64.tar.gz
  #     . ~/.bashrc # exec bash
  #     gcloud auth login
  #     read -p "Enter Your GCP Project ID: " GCP_ID
  #     gcloud config set project $GCP_ID
  #     export GCLOUD_PROJECT=$GCP_ID
  #     eval "echo -e '\nexport GCLOUD_PROJECT="$GCP_ID"' >> ~/.bashrc"
  #     gcloud auth application-default login
  #     pip install -r requirements2.txt
  #   openMode: split-right
vscode:
  extensions:
    - timonwong.shellcheck
  
